# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MyUI4.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(725, 555)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 1, 4, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.widget)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 3, 1, 1)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.widget)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.gridLayout_2.addWidget(self.dateTimeEdit, 0, 2, 1, 1)
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(self.widget)
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.gridLayout_2.addWidget(self.dateTimeEdit_2, 1, 2, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setItemText(23, "")
        self.gridLayout_2.addWidget(self.comboBox, 0, 4, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.widget)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 0, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.widget)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 1, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 5, 1, 1)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout.setObjectName("gridLayout")
        self.label_10 = QtWidgets.QLabel(self.widget_3)
        self.label_10.setStyleSheet("color: rgb(132, 132, 0);")
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget_3)
        self.label_6.setStyleSheet("color: rgb(255, 85, 0);")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.widget_3)
        self.label_13.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 3, 5, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget_3)
        self.label_5.setStyleSheet("color: rgb(0, 170, 0);")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.widget_3)
        self.label_12.setStyleSheet("color: rgb(109, 109, 163);")
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 2, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setStyleSheet("color: rgb(0, 170, 0);")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.widget_3)
        self.label_14.setStyleSheet("color: rgb(255, 85, 0);")
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 2, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget_3)
        self.label_7.setStyleSheet("color: rgb(85, 0, 255);")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.widget_3)
        self.label_18.setStyleSheet("color: rgb(132, 132, 0);")
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 3, 4, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.widget_3)
        self.label_15.setStyleSheet("color: rgb(85, 0, 255);")
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 3, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.widget_3)
        self.label_17.setStyleSheet("color: rgb(170, 0, 0);")
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 2, 4, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget_3)
        self.label_9.setStyleSheet("color: rgb(170, 0, 0);")
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget_3)
        self.label_11.setStyleSheet("color: rgb(48, 144, 144);")
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 1, 5, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget_3)
        self.label_8.setStyleSheet("color: rgb(255, 0, 255);")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 3, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.widget_3)
        self.label_16.setStyleSheet("color: rgb(255, 0, 255);")
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 1, 4, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.widget_3)
        self.label_19.setStyleSheet("color: rgb(48, 144, 144);")
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 1, 6, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.widget_3)
        self.label_20.setStyleSheet("color: rgb(109, 109, 163);")
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 2, 6, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.widget_3)
        self.label_21.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 3, 6, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 7, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setStyleSheet("text-decoration: underline;")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 3, 1, 1)
        self.verticalLayout.addWidget(self.widget_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Запрос"))
        self.label_24.setText(_translate("MainWindow", "Конец отсчёта:"))
        self.label.setText(_translate("MainWindow", "Рабочее место:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Участок полностью"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Лазер №1"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Лазер №2"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Лазер №3"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Пробика №1"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Пробивка №2"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Гибка №1"))
        self.comboBox.setItemText(7, _translate("MainWindow", "Гибка №2"))
        self.comboBox.setItemText(8, _translate("MainWindow", "Гибка №3"))
        self.comboBox.setItemText(9, _translate("MainWindow", "Гибка №4"))
        self.comboBox.setItemText(10, _translate("MainWindow", "Гибка №5"))
        self.comboBox.setItemText(11, _translate("MainWindow", "Гибка №6"))
        self.comboBox.setItemText(12, _translate("MainWindow", "Гибка №7"))
        self.comboBox.setItemText(13, _translate("MainWindow", "Сварка №1"))
        self.comboBox.setItemText(14, _translate("MainWindow", "Сварка №2"))
        self.comboBox.setItemText(15, _translate("MainWindow", "Сварочный робот №1"))
        self.comboBox.setItemText(16, _translate("MainWindow", "Сварочный робот №2"))
        self.comboBox.setItemText(17, _translate("MainWindow", "Сварочный робот №3"))
        self.comboBox.setItemText(18, _translate("MainWindow", "Сварочный робот №4"))
        self.comboBox.setItemText(19, _translate("MainWindow", "Сборка №1"))
        self.comboBox.setItemText(20, _translate("MainWindow", "Сборка №2"))
        self.comboBox.setItemText(21, _translate("MainWindow", "Зачистка №1"))
        self.comboBox.setItemText(22, _translate("MainWindow", "Зачистка №2"))
        self.label_23.setText(_translate("MainWindow", "Начало отсчёта:"))
        self.label_22.setText(_translate("MainWindow", "Ручной ввод:"))
        self.label_10.setText(_translate("MainWindow", "TextLabel"))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.label_13.setText(_translate("MainWindow", "TextLabel"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
        self.label_12.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_14.setText(_translate("MainWindow", "TextLabel"))
        self.label_7.setText(_translate("MainWindow", "TextLabel"))
        self.label_18.setText(_translate("MainWindow", "TextLabel"))
        self.label_15.setText(_translate("MainWindow", "TextLabel"))
        self.label_17.setText(_translate("MainWindow", "TextLabel"))
        self.label_9.setText(_translate("MainWindow", "TextLabel"))
        self.label_11.setText(_translate("MainWindow", "TextLabel"))
        self.label_8.setText(_translate("MainWindow", "TextLabel"))
        self.label_16.setText(_translate("MainWindow", "TextLabel"))
        self.label_19.setText(_translate("MainWindow", "TextLabel"))
        self.label_20.setText(_translate("MainWindow", "TextLabel"))
        self.label_21.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
